### ISSUE TITLE
npm start 执行报错

### ISSUE THREAD

**Issue by wraptor** [zuoyanart/sparender#4]
![](https://gitee.com/seepine/oss/raw/master/picgo/20210130213044.png)

```
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/root/sparender/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/root/sparender/node_modules/redis-parser/lib/parser.js:302:14)
```

**Comment by zuoyanart** [comment]
你这个是redis授权的问题,  看看是不是设置了密码
